### ISSUE TITLE
zetafuacet binary from yarn global add doesn't work

### ISSUE THREAD

**Issue by xpanvictor** [zeta-chain/template#20]
The zetafaucet binary doesnt work. I suppose it's a general issue with yarn, check [here](https://github.com/yarnpkg/yarn/issues/5353).
However,  npx zetafaucet -h worked. If okay, could be changed in the docs.

**Comment by fadeev** [comment]
@xpanvictor after you install the faucet:

```
yarn global add @zetachain/faucet-cli@athens3
```

Can you try running it directly:

```
/usr/local/bin/zetafaucet
```

Do you have `/usr/local/bin` in the output of `echo $PATH`?

**Comment by xpanvictor** [comment]
> 

I did that and still didn't work
and yes, I have usr/local/bin in my PATH variable

**Comment by fadeev** [comment]
`zetafaucet` has been updated since and should be working fine with `yarn`.
